[package]
name = "buffer"
version = "0.1.0"
description = "A simple buffer interface and helper function to have different underlying storage types."
repository = "https://github.com/edjcase/motoko_buffer"
keywords = ["buffer", "list", "array", "write"]
license = "MIT"

[dependencies]
"base@0" = "0.16.0"
"core@1" = "1.0.0"

[dev-dependencies]
test = "2.1.1"
