[package]
name = "buffer"
version = "0.0.1"
description = "A simple buffer interface and helper function to have different underlying storage types."
repository = "https://github.com/edjcase/motoko_buffer"
keywords = ["buffer", "list", "array", "write"]
license = "MIT"

[dependencies]
base = "0.15.1"
core = "0.6.0"

[dev-dependencies]
test = "2.1.1"
